-- 코드를 입력하세요
SELECT
DISTINCT(PRODUCT_CODE) AS PRODUCT_CODE ,
SUM(PRICE * SALES_AMOUNT) AS SALES

FROM
PRODUCT A
JOIN
OFFLINE_SALE B
ON
A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY
PRODUCT_CODE

ORDER BY
    SALES DESC, PRODUCT_CODE ASC