-- 코드를 입력하세요
SELECT
A.ANIMAL_ID,
B.ANIMAL_TYPE,
A.NAME
FROM
ANIMAL_INS A
JOIN
ANIMAL_OUTS B
ON
A.ANIMAL_ID = B.ANIMAL_ID

WHERE
# SEX_UPON_INTAKE LIKE 'Spayed ' 
SUBSTRING_INDEX(SEX_UPON_INTAKE, ' ', 1) =  'Intact' AND
(SUBSTRING_INDEX(SEX_UPON_OUTCOME, ' ', 1) =  'Spayed' OR
SUBSTRING_INDEX(SEX_UPON_OUTCOME, ' ', 1) =  'Neutered' )
# SQL 은 인덱스 1부터 시작이랍니다.

ORDER BY
ANIMAL_ID