SELECT TITLE

    , a.BOARD_ID
    , REPLY_ID
    , R.WRITER_ID
    , R.CONTENTS
    , DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') CREATED_DATE

FROM 
	USED_GOODS_BOARD AS A, 
	USED_GOODS_REPLY AS R

WHERE a.BOARD_ID = R.BOARD_ID
	AND a.CREATED_DATE BETWEEN '2022-10-01'
	AND '2022-10-31'

ORDER BY 
	r.CREATED_DATE ASC, 
	TITLE ASC;
